### ISSUE TITLE
Netherlands (Amsterdam / Rotterdam / Eindhoven) request

### ISSUE THREAD

**Issue by ArkadiyD** [gmberton/awesome-machine-learning-startups#1]
Hey, awesome project! Would it be possible to add Amsterdam (+Rotterdam / Eindhoven) locations? I think there should be quite a lot of interesting ones. Thanks!

**Comment by gmberton** [comment]
Done!

**Comment by ArkadiyDushatskiy-TomTom** [comment]
Awesome, thank you!
