### ISSUE TITLE
Robotics Labs (Pvt) Ltd. Link not working

### ISSUE THREAD

**Issue by Shrinidhibhat87** [gmberton/awesome-machine-learning-startups#2]
What is the issue?

It looks like the link to the above company's website (myrobotics.net) does not work and the user is prompted to decide if they want to buy the domain. I have attached the screenshot as well. 

Screenshot:

<img width="773" alt="image" src="https://github.com/user-attachments/assets/dc32b980-f93c-4a5e-b1fa-a2bcba52bc1e">

Solution:

Searching the company name prompts the reader to their LinkedIn account. Therefore, removing the company listed there or changing this with its LinkedIn account link are the possible solutions.

Let me know if you want me to create a PR based on the above solutions.

**Comment by gmberton** [comment]
I fixed it by using their linkedin page as website
